server:
    port: 8761

eureka:
    instance:
        hostname: eureka-server
        prefer-ip-address: false
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    server:
        enable-self-preservation: false